version: '3'

services:
  # Сервис Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  # Сервис Redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # Сервис Celery
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    env_file:
      - .env
    depends_on:
      - web
      - redis
    command: ["celery", "-A", "config", "worker", "-l", "info"]


