# Generated by Django 4.2.7 on 2023-11-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('time_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_habit', models.CharField(max_length=100)),
                ('description_habit', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=200)),
                ('is_pleasurable', models.BooleanField(default=False)),
                ('periodicity', models.PositiveIntegerField(default=1)),
                ('reward', models.CharField(max_length=200)),
                ('estimated_time', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('linked_habits', models.ManyToManyField(blank=True, to='habit.habit')),
                ('name_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('name_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_location.time')),
            ],
            options={
                'verbose_name': 'Привычки',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
